import '../styles/globals.css';
import StyledComponentsRegistry from '../lib/AntdRegistry';

import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
config.autoAddCss = false;

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from '@/redux/provider';
import dynamic from 'next/dynamic';

const MLayout = dynamic(() => import('@/layout/MLayout'), { ssr: false });
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<StyledComponentsRegistry>
					<Providers>
						<MLayout>{children}</MLayout>
					</Providers>
				</StyledComponentsRegistry>
			</body>
		</html>
	);
}
